image: gitpod/workspace-full:latest
tasks:
  - before: sdk install java 23-oracle < /dev/null
  - name: initialize
    command: |
      mkdir -p .vscode
      mkdir -p ~/.local/bin/
      echo '{"python.defaultInterpreterPath": "/home/gitpod/micromamba/envs/env/bin/python"}' > .vscode/settings.json
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C ~/.local/ bin/micromamba
      ~/.local/bin/micromamba shell init -s bash -p ~/micromamba -y
      source ~/.bashrc
      micromamba create -n dataproduct -c defaults python=3.11 -y
      micromamba activate dataproduct  
      sudo service docker start 
      eval "$(micromamba shell hook --shell bash)"
      gp sync-done mm
  

  - name: Install dataproduct CLI     
    command: |
      wget -O cli.zip "https://repository.uitwisselingsplatform.be/service/rest/v1/search/assets/download?repository=ddt-public-releases&group=be.ddtplatform&name=data-product-cli&sort=version&prerelease=false&maven.extension=zip"
      unzip "cli.zip"
      cd "dp-cli-installer"
      bash "installer-mac-linux.sh"
      cd ..
      rm -rf "wget-log" "cli.zip" "dp-cli-installer"
      mkdir -p /home/gitpod/.ddt/dp/data/fuseki
      chmod 777 -R /home/gitpod/.ddt/dp/data/fuseki
      echo "
      ** Waiting until Java and Micromamba have finished installing, this can take up to a minute so please wait a few moments... **"
      gp sync-await mm
      eval "$(micromamba shell hook --shell bash)"
      micromamba activate dataproduct