apiVersion: be.ddtplatform/v1
kind: DataProduct
metadata:
  name: "demo-dataproduct"  # Do not change this name.
  namespace: "dp-be-publiq-demo"  # Do not change this namespace.
spec:
  summary: |          # A summary, describing the data product.
    "Hello world" dataproduct als onboarding voorbeeld voor data product developers
  domain: "be.publiq.demo"  # Do not change this domain. It is the domain owning the data project. This is a functional business domain often discovered using techniques from domain driven design.
  termsOfUse:         #  The terms for using this data product and its data.
    name: "Creative Commons Attribution 4.0 International"
    uri: "https://creativecommons.org/licenses/by/4.0/legalcode.nl"
  dataProductOwner:   # The owner of the data product. Contact this person for information about the business around the data product
    name: "Stan Vertessen"
    contact: "stan.vertessen@publiq.be"
  responsibleTechnicalTeam:  # The technical team owning this data product and responsible for implementing, adapting, and deploying it. Contact this team for changes in requirements, feedback, technical issues, etc
    name: "Stan Vertessen"
    contact: "stan.vertessen@publiq.be"
  transformer:
    schedule: "0 */6 * * *"    # cron schedule op minuut 0 elke 6u
  inputPorts:                  
    - name: "myInputPortName"  # het demo dataproduct gebruikt geen input poort, maar deze variabele is wel verplicht in data product spec 
  outputPorts:
    - name: "demosparql"       # deze variabele wordt gebruikt door de transformatie code van het demo dataproduct
      type: linkeddata         # deze variabele zorgt ervoor dat er een fuseki instance geinitialiseerd wordt
      description: "This outputport contains one or more sample entities as a result of demo transformation code for onboarding data product developers"        
      dataFormat:
        description: "RDF/OSLO compliant entity example as described here: https://uitwisselingsplatform.atlassian.net/wiki/spaces/DDTC/pages/321388562/Domein+Entiteiten"
        entityExample: "Locatie, Activiteit, Deelname, Participant voorbeelden"
        linkedDataSchemaDefinition: "[TODO]" 
